language: cpp
matrix:
  include:
    - os: linux
      services:
        - docker
      env:
        - BUILD_APIDOC=true
        # Auth token to push API documentation
        - secure: "JKeXk8p65hodb12PVRST6A90swsNubc+46EbSJGSghldIxbFWLBAlwU+KLeOMO4V0veu6k4lnMa50V0UYFZmoUsS6W0aL5Ybo98SpzXHiNLOmOluoqJoF9TBsOTCCRFbWbccgJyVEtulgRcdml96naS51lq9Sw/VO/N3Z472304="
    - os: linux
      services:
        - docker
    - os: osx
      osx_image: xcode6.4
      compiler: clang
  allow_failures:
    - env:
      - BUILD_APIDOC=true
      - secure: "JKeXk8p65hodb12PVRST6A90swsNubc+46EbSJGSghldIxbFWLBAlwU+KLeOMO4V0veu6k4lnMa50V0UYFZmoUsS6W0aL5Ybo98SpzXHiNLOmOluoqJoF9TBsOTCCRFbWbccgJyVEtulgRcdml96naS51lq9Sw/VO/N3Z472304="
install:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # Download build environment in a docker container
      docker pull freeorion/freeorion-travis-build
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      wget https://github.com/freeorion/freeorion-sdk/releases/download/v3/FreeOrionSDK_3_Clang-MacOSX-10.7-i386.dmg
      hdiutil attach FreeOrionSDK_3_Clang-MacOSX-10.7-i386.dmg
      tar -xjf /Volumes/FreeOrionSDK/dep.tar.bz2 -C Xcode
      hdiutil detach /Volumes/FreeOrionSDK
    fi
before_script:
  # Configure git to use the identity of FreeOrion Build Bot and
  # load credentials
  - >
    if [[ "${BUILD_APIDOC}" == "true" ]]; then
      git config --global user.email "freeorionorg@gmail.com"
      git config --global user.name "FreeOrion Build Bot"
      git config --global credential.helper "cache --timeout=300"
      echo -e "url=https://freeorion-bot:${FreeOrion_AUTH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git\n" | git credential approve
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir build
      cd build
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      cd Xcode
    fi
script:
  - >
    if [[ "${BUILD_APIDOC}" == "true" && "${TRAVIS_BRANCH}" == "master" ]]; then
      docker run -v "${TRAVIS_BUILD_DIR}:/src" -v "$(pwd):/build" -w /build freeorion/freeorion-travis-build cmake /src
      docker run -v "${TRAVIS_BUILD_DIR}:/src" -v "$(pwd):/build" -w /build freeorion/freeorion-travis-build cmake --build . --target apidoc-deploy
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" && -z "${BUILD_APIDOC}" ]]; then
      docker run -v "${TRAVIS_BUILD_DIR}:/src" -v "$(pwd):/build" -w /build freeorion/freeorion-travis-build cmake /src
      docker run -v "${TRAVIS_BUILD_DIR}:/src" -v "$(pwd):/build" -w /build freeorion/freeorion-travis-build cmake --build . -- -j 2
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      xcodebuild -project FreeOrion.xcodeproj -configuration Release -alltargets
    fi
